"""
Services — Dashboard Service
Queries SQLite for aggregate statistics.
"""

import logging
from datetime import datetime, timedelta, timezone

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.chat import ChatHistory
from app.models.paper import Paper
from app.models.report import Report
from app.models.user import User

logger = logging.getLogger("app")


async def get_user_dashboard(db: AsyncSession, user_id: int) -> dict:
    """
    Return dashboard statistics for the current user.
    """
    # Total papers
    total_papers_result = await db.execute(
        select(func.count(Paper.paper_id)).where(Paper.user_id == user_id)
    )
    total_papers = total_papers_result.scalar_one() or 0

    # Papers ready
    ready_papers_result = await db.execute(
        select(func.count(Paper.paper_id)).where(
            Paper.user_id == user_id, Paper.status == "ready"
        )
    )
    ready_papers = ready_papers_result.scalar_one() or 0

    # Total reports generated by user
    total_reports_result = await db.execute(
        select(func.count(Report.id))
        .join(Paper, Report.paper_id == Paper.paper_id)
        .where(Paper.user_id == user_id)
    )
    total_reports = total_reports_result.scalar_one() or 0

    # Total Q&A interactions
    total_qa_result = await db.execute(
        select(func.count(ChatHistory.id)).where(ChatHistory.user_id == user_id)
    )
    total_qa = total_qa_result.scalar_one() or 0

    # Recent papers (last 5)
    recent_papers_result = await db.execute(
        select(Paper)
        .where(Paper.user_id == user_id)
        .order_by(Paper.upload_date.desc())
        .limit(5)
    )
    recent_papers = [
        {
            "paper_id": p.paper_id,
            "title": p.title or p.filename,
            "status": p.status,
            "upload_date": p.upload_date.isoformat() if p.upload_date else None,
        }
        for p in recent_papers_result.scalars().all()
    ]

    return {
        "total_papers": total_papers,
        "ready_papers": ready_papers,
        "processing_papers": total_papers - ready_papers,
        "total_reports": total_reports,
        "total_qa_interactions": total_qa,
        "recent_papers": recent_papers,
    }


async def get_admin_stats(db: AsyncSession) -> dict:
    """
    Return admin-level aggregate statistics.
    """
    # Total users
    total_users_result = await db.execute(select(func.count(User.id)))
    total_users = total_users_result.scalar_one() or 0

    # Total papers
    total_papers_result = await db.execute(select(func.count(Paper.paper_id)))
    total_papers = total_papers_result.scalar_one() or 0

    # Total reports
    total_reports_result = await db.execute(select(func.count(Report.id)))
    total_reports = total_reports_result.scalar_one() or 0

    # Total QA
    total_qa_result = await db.execute(select(func.count(ChatHistory.id)))
    total_qa = total_qa_result.scalar_one() or 0

    # Papers by status
    status_result = await db.execute(
        select(Paper.status, func.count(Paper.paper_id)).group_by(Paper.status)
    )
    papers_by_status = {row[0]: row[1] for row in status_result.all()}

    # Recent registrations (last 7 days)
    seven_days_ago = datetime.now(timezone.utc) - timedelta(days=7)
    new_users_result = await db.execute(
        select(func.count(User.id)).where(User.created_at >= seven_days_ago)
    )
    new_users_this_week = new_users_result.scalar_one() or 0

    return {
        "total_users": total_users,
        "total_papers": total_papers,
        "total_reports": total_reports,
        "total_qa_interactions": total_qa,
        "papers_by_status": papers_by_status,
        "new_users_this_week": new_users_this_week,
    }
