"""
API — Reports Routes
GET  /api/reports
GET  /api/reports/{report_id}/download
GET  /api/dashboard
"""

import logging
from pathlib import Path

from fastapi import APIRouter, Depends
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report
from app.models.paper import Paper
from app.models.user import User
from app.schemas.report import ReportResponse, ReportsListResponse
from app.services.dashboard_service import get_user_dashboard
from app.utils.dependencies import get_current_user, get_db
from app.utils.exceptions import ForbiddenException, NotFoundException

router = APIRouter(tags=["Reports & Dashboard"])
logger = logging.getLogger("app")


# ── GET /api/reports ──────────────────────────────────────────────────────────

@router.get(
    "/api/reports",
    response_model=ReportsListResponse,
    summary="List all generated reports for the current user",
)
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ReportsListResponse:
    """Return all reports generated by the current user."""
    result = await db.execute(
        select(Report)
        .join(Paper, Report.paper_id == Paper.paper_id)
        .where(Paper.user_id == current_user.id)
        .order_by(Report.created_at.desc())
    )
    reports = list(result.scalars().all())

    return ReportsListResponse(
        total=len(reports),
        reports=[ReportResponse.model_validate(r) for r in reports],
    )


# ── GET /api/reports/{report_id}/download ────────────────────────────────────

@router.get(
    "/api/reports/{report_id}/download",
    summary="Download a generated report file",
)
async def download_report(
    report_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> FileResponse:
    """Download a previously generated PDF or DOCX report."""
    # Get report
    report_result = await db.execute(
        select(Report).where(Report.id == report_id)
    )
    report = report_result.scalar_one_or_none()
    if not report:
        raise NotFoundException("Report")

    # Verify ownership through paper
    paper_result = await db.execute(
        select(Paper).where(Paper.paper_id == report.paper_id)
    )
    paper = paper_result.scalar_one_or_none()
    if not paper or paper.user_id != current_user.id:
        raise ForbiddenException("You do not have permission to access this report.")

    # Check file exists
    report_path = Path(report.report_path)
    if not report_path.exists():
        raise NotFoundException("Report file")

    media_type = "application/pdf" if report.format == "pdf" else (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )

    return FileResponse(
        path=str(report_path),
        media_type=media_type,
        filename=report_path.name,
    )


# ── GET /api/dashboard ────────────────────────────────────────────────────────

@router.get(
    "/api/dashboard",
    summary="Get dashboard statistics for the current user",
)
async def get_dashboard(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> dict:
    """Return aggregated statistics for the authenticated user's dashboard."""
    stats = await get_user_dashboard(db, current_user.id)
    return {"success": True, "data": stats}
